language: ruby
cache: bundler
sudo: false
rvm:
- 1.9.3
branches:
  except:
  - CURRENT
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - ! '%{repository} %{branch} - %{message} %{build_url}'
    on_success: change
    on_failure: always
env:
  global:
  - COURSES_TARGET_URL: http://test.host/courses.json
  - CAPSULECRM_ACCOUNT_NAME: something
  - CAPSULECRM_API_TOKEN: something_else
  - CAPSULECRM_DEFAULT_OWNER: defaultuser
  - EVENTBRITE_API_KEY: hello
  - EVENTBRITE_USER_KEY: user
  - EVENTBRITE_ORGANIZER_ID: '1234'
  - RACKSPACE_USERNAME: raxdemotheodi
  - RACKSPACE_CONTAINER: test-container
  - GAPPS_FINANCE_SPOOL_COLLECTION: spool
  - GAPPS_FINANCE_TARGET_COLLECTION: target
  - GAPPS_FINANCE_TARGET_KEY: random_numbers
  - GAPPS_PASSWORD: password
  - GAPPS_USER_EMAIL: test@example.com
  - TRELLO_DEV_KEY: devkey
  - TRELLO_MEMBER_KEY: memberkey
  - XERO_CONSUMER_KEY: consumerkey
  - XERO_CONSUMER_SECRET: consumersecret
  - XERO_PRIVATE_KEY_PATH: certs/test/privatekey.pem
  - secure: IW7M+OHx2LpdLYhlI55rVMK5sceD+qk+/b4bYEnLnOJJkbs0Cj4n2rBF7NT/BJd4Z6wiugEn6oedII0Y6w/0PxDAfYQc0O0BT39zgqnReeRt4fc1AGcCbu0n8K6aJlKL97WId6pkp00v2GWSYlc5B1WccDvdn9eq2QNRR7kKxQE=
