language: ruby
cache: bundler
sudo: false
rvm:
- 2.3.0
branches:
  except:
  - CURRENT
notifications:
  irc:
    channels:
    - irc.freenode.net#theodi
    template:
    - ! '%{repository} %{branch} - %{message} %{build_url}'
    on_success: change
    on_failure: always
env:
  global:
  - COURSES_TARGET_URL: http://test.host/courses.json
  - CAPSULECRM_ACCOUNT_NAME: something
  - CAPSULECRM_API_TOKEN: something_else
  - CAPSULECRM_DEFAULT_OWNER: defaultuser
  - CHARGIFY_API_KEY: chargifykey
  - CHARGIFY_SUBDOMAIN: theodi-testing
  - EVENTBRITE_API_KEY: hello
  - EVENTBRITE_USER_KEY: user
  - EVENTBRITE_ORGANIZER_ID: '1234'
  - FINANCE_EMAIL: finance@example.org
  - RACKSPACE_USERNAME: raxdemotheodi
  - RACKSPACE_CONTAINER: test-container
  - GAPPS_FINANCE_SPOOL_COLLECTION: spool
  - GAPPS_FINANCE_TARGET_COLLECTION: target
  - GAPPS_FINANCE_TARGET_KEY: random_numbers
  - GAPPS_PASSWORD: password
  - GAPPS_USER_EMAIL: test@example.com
  - MAILING_LIST_LIST_ID: 3089417f22
  - TRELLO_DEV_KEY: devkey
  - TRELLO_MEMBER_KEY: memberkey
  - XERO_PRIVATE_KEY_PATH: certs/test/privatekey.pem
  - secure: IW7M+OHx2LpdLYhlI55rVMK5sceD+qk+/b4bYEnLnOJJkbs0Cj4n2rBF7NT/BJd4Z6wiugEn6oedII0Y6w/0PxDAfYQc0O0BT39zgqnReeRt4fc1AGcCbu0n8K6aJlKL97WId6pkp00v2GWSYlc5B1WccDvdn9eq2QNRR7kKxQE=
  - secure: Ii/blMJCX5cnhYwO/GYbNKxNw+//jnB/lAEPByPUUezSIZVN1mJN3zyttz7ektZ9czMSlwkr+srhEd1fFS7XwXbvLOc+TaajfGiidWnyhr7xtIultLJ08K0aWr4QF2WtdDgZ/qg8Z5f5xzkF45zP1gqSaxJvaJDz/1G7r0rvRXE=
  - secure: WONuMwHUjBkfb4R2/5kTRquHR0yZ81DRWfu0DLZZOEyCe7YN5isg+mDWj/krC40pa89UPYURRQYJp2/cRB8F4yz0TAKiypaxceOo6wwCzFyPcQbeGCCTlSLfTHYi5yjJ+e7hkj/u+6Ae1SW2UjPIaUuUTzI5QfxqO9Z61edzfcE=
  - secure: Bp0NVp0CryFR2+ZFzGTIXjGuU0DnwIByTWBqZpA3CGhI0rRMTuo8qphNkCgiDXoOCXjZDdTWvIodxQPNmZwlUR718mrrsR0cZ51J1bcHpMB/x5md3+yhD92V3b2eJl47YxT3nQvx5ws14ryizyOgxnPUcfclD3AWeTCE0KMwqDU=
  - secure: XmnCzyHMcAgoNzYg/rW0975UmfFrivvz0gYmb+C0YU2tY+cgBQyjj+WHJogOoUnRlAA4bfZOVcvbY7NvOLYY0ts4SoMdlvoN0bRO+HZjpfeefi8zhx5qhiAKK6huvTE9psAOOGMrUS+xuqhMC5B+9ziwZrLBRA45zkyd+goHIWw=
