2013:
  Reach:        B1
  Bookings:     B4
  Value unlocked: B3
  KPI percentage: B2

2014:
  Network size: I24
  Members:      I25
  Nodes:        I26
  Startups:     I27
  Affiliates:   I28
  Reach:        B1
  Bookings:     B4
  Value unlocked: B3
  KPI percentage: B2
