document_keys:

  development:
    dashboard: 0Aon_avj5tPqbdElsdWp1eDA3bEtyZkZweWhjUllBMHc
    budget: 0Ak-lNj2cKAaydHJwbk1YVmRtUXc3YmtZMzNLd1NERGc
  test:
    dashboard: 0Aon_avj5tPqbdElsdWp1eDA3bEtyZkZweWhjUllBMHc
    budget: 0Ak-lNj2cKAaydHJwbk1YVmRtUXc3YmtZMzNLd1NERGc
  production:
    dashboard: 0Aon_avj5tPqbdElsdWp1eDA3bEtyZkZweWhjUllBMHc
    budget: 0Ak-lNj2cKAaydHJwbk1YVmRtUXc3YmtZMzNLd1NERGc

cell_lookups:

  2013:

    Reach:
      cell_ref: B1
      sheet: 2013
      document: dashboard
    Bookings:
      cell_ref: B4
      sheet: 2013
      document: dashboard
    Value unlocked:
      cell_ref: B3
      sheet: 2013
      document: dashboard
    KPI percentage:
      cell_ref: B2
      sheet: 2013
      document: dashboard

  2014:

    Network size:
      cell_ref: I24
      sheet: 2014
      document: dashboard
    Members:
      cell_ref: I25
      sheet: 2014
      document: dashboard
    Nodes:
      cell_ref: I26
      sheet: 2014
      document: dashboard
    Startups:
      cell_ref: I27
      sheet: 2014
      document: dashboard
    Affiliates:
      cell_ref: I28
      sheet: 2014
      document: dashboard
    Reach:
      cell_ref: B1
      sheet: 2014
      document: dashboard
    Bookings:
      cell_ref: B4
      sheet: 2014
      document: dashboard
    Value unlocked:
      cell_ref: B3
      sheet: 2014
      document: dashboard
    KPI percentage:
      cell_ref: B2
      sheet: 2014
      document: dashboard
    Total income:
      cell_ref: G12
      sheet: Summary
      document: budget
