dashboard_time:
  every: 1m
  class: DashboardTime
  args:
  description: "Updates the time on the dashboard every 1 minute"
  
github:
  every: 1h
  class: GithubMonitor
  args:
  description: "Pulls information from Github"
  
trello:
  every: 5m
  class: TrelloMonitor
  args:
  description: "Pulls information from Trello"

build_status:
  every: 1m
  class: BuildStatusMonitor
  args:
  description: "Check Jenkins build status"
  
eventbrite:
  every: 1h
  class: EventLister
  args:
  description: "Interrogate all events in Eventbrite"
